logging:
  file:
    name: logs/api.log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    org.msa.eureka: debug

spring:
  application:
    name: eureka
server:
  port: 8761
eureka:
  instance:
    hostname: eureka
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

    register-with-eureka: false
    fetch-registry: false